### ISSUE TITLE
NameError: name "max_pool2d" is not defined

### ISSUE THREAD

**Issue by Haidexter001** [xinDW/LFRNet#5]
I'm trying to run your LFRNet code as a part of a student project I'm currently conducting. I've created a virtual environment in Anaconda and installed all the required packages given in the requirements.txt file.

My tensorflow installation is GPU enabled with CUDA 10 and cudnn 7.6.

Whenever I try to run eval.py for the inference, I get the following error:

` _WARNING:tensorflow:From user\Documents\LFRNet-master\tensorlayer\layers\core.py:55: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From user\Documents\LFRNet-master\tensorlayer\layers\pooling.py:66: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

[TL] [!] example_data/valid/bead/VCD_bead_40x_[m30-30]_step1um/ exists ...
user\anaconda3\envs\Tensorflow Final\lib\site-packages\imageio\plugins\_tifffile.py:7285: UserWarning: module 'imageio.plugins._tifffile' has no attribute 'decode_packbits'
  Functionality might be degraded or be slow.

  warnings.warn("%s%s" % (e, warn))
user\anaconda3\envs\Tensorflow Final\lib\site-packages\imageio\plugins\_tifffile.py:7285: UserWarning: module 'imageio.plugins._tifffile' has no attribute 'decode_lzw'
  Functionality might be degraded or be slow.

  warnings.warn("%s%s" % (e, warn))
user\anaconda3\envs\Tensorflow Final\lib\site-packages\imageio\plugins\_tifffile.py:7285: UserWarning: module 'imageio.plugins._tifffile' has no attribute 'unpack_ints'
  Functionality might be degraded or be slow.

  warnings.warn("%s%s" % (e, warn))
user\envs\Tensorflow Final\lib\site-packages\imageio\plugins\_tifffile.py:7285: UserWarning: module 'imageio.plugins._tifffile' has no attribute 'reverse_bitorder'
  Functionality might be degraded or be slow.

  warnings.warn("%s%s" % (e, warn))
read 1 from example_data/valid/bead/
WARNING:tensorflow:From eval.py:64: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From user\Documents\LFRNet-master\model\unet.py:166: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From user\Documents\LFRNet-master\tensorlayer\layers\core.py:410: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

[TL] InputLayer  unet/lf_extra: (1, 84, 83, 121)
[TL] Conv2d unet/conv1/conv: shape:(5, 5, 121, 128) strides:(1, 1, 1, 1) pad:SAME act:identity
WARNING:tensorflow:From user\Documents\LFRNet-master\tensorlayer\layers\convolution.py:1481: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From user\anaconda3\envs\Tensorflow Final\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:

Call initializer instance with the dtype argument instead of passing it to the constructor

[TL] SubpixelConv2d  upsale0/subpixel: scale: 2 n_out_channel: None act: identity
[TL] Conv2d unet/interp/upsale0/conv: shape:(3, 3, 32, 64) strides:(1, 1, 1, 1) pad:SAME act:identity
[TL] SubpixelConv2d  upsale1/subpixel: scale: 2 n_out_channel: None act: identity
[TL] Conv2d unet/interp/upsale1/conv: shape:(3, 3, 16, 32) strides:(1, 1, 1, 1) pad:SAME act:identity
[TL] SubpixelConv2d  upsale2/subpixel: scale: 2 n_out_channel: None act: identity
[TL] Conv2d unet/interp/upsale2/conv: shape:(3, 3, 8, 16) strides:(1, 1, 1, 1) pad:SAME act:identity
[TL] SubpixelConv2d  upsale3/subpixel: scale: 2 n_out_channel: None act: identity
[TL] Conv2d unet/interp/upsale3/conv: shape:(3, 3, 4, 8) strides:(1, 1, 1, 1) pad:SAME act:identity
[TL] Conv2d unet/encoder/conv0/conv: shape:(3, 3, 8, 64) strides:(1, 2, 2, 1) pad:SAME act:identity
encoder 0 : (1, 672, 664, 64)
[TL] Conv2d unet/encoder/conv1/conv: shape:(3, 3, 64, 64) strides:(1, 1, 1, 1) pad:SAME act:identity
Traceback (most recent call last):
  File "eval.py", line 128, in <module>
    infer(ckpt, batch_size=batch_size, use_cpu=use_cpu)
  File "eval.py", line 69, in infer
    net = UNet_B(t_image, n_slices, [height * n_num, width * n_num], is_train=True, reuse=False, name='unet')
  File "user\Documents\LFRNet-master\model\unet.py", line 189, in UNet_B
    n = max_pool2d(n, filter_size=2, stride=2)
NameError: name 'max_pool2d' is not defined_ `

I'm quite new to tensorflow, and this is an essential process for my project in light field microscopy, so I would greatly appreciate any kind of help to resolve the matter.

**Comment by xinDW** [comment]
Hi,&nbsp;


The error results from a missing declaration of the function 'max_pool2d' in model/util/utils.py. I have had it fixed on the GitHub repository:&nbsp;utils.py.&nbsp;


Please let me known if there are other coding errors.


------------------&nbsp;Original&nbsp;------------------
